# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: default task
    deps:
      - build

  build:
    desc: Build certsuck cli
    cmds:
    - cmd: go build -o releases/certsuck ./cmd/suck

  install:
    desc: Build and install certsuck
    cmds:
    - cmd: go install ./cmd/certsuck